apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-operator
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - thanosrulers
  verbs:
  - list
  - get
  - watch
