apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki
    spec:
      containers:
      - image: docker.io/grafana/loki:2.2.1
        name: loki
        ports:
        - containerPort: 3100
        volumeMounts:
        - mountPath: /loki
          name: storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: loki
