apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observatorium

resources:
- promtail-clusterrolebinding.yaml
- promtail-clusterrole.yaml
- promtail-ds.yaml
- promtail-sa.yaml

vars:
- fieldref:
    fieldPath: metadata.namespace
  name: NAMESPACE
  objref:
    apiVersion: apps/v1
    kind: DaemonSet
    name: promtail

configurations:
- kustomizeconfig.yaml
