apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- files:
  - promtail.yaml=conf/promtail.yaml
  name: promtail
  options:
    disableNameSuffixHash: true

bases:
- ../../base
