apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
spec:
  template:
    spec:
      containers:
      - args:
        - -config.file=/etc/promtail/promtail.yaml
        - -client.url=http://loki.loki.svc.cluster.local:3100/api/prom/push
        - -client.external-labels=hostname=$(HOSTNAME),cluster=mycluster
        name: promtail
