apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
spec:
  template:
    spec:
      containers:
      - name: promtail
        volumeMounts:
        - name: promtail-certs
          mountPath: /etc/promtail/certs
          readOnly: true
      volumes:
      - name: promtail-certs
        secret:
          secretName: promtail-certs
