apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operated
  labels:
    app: prometheus-operated
spec:
  endpoints:
  - port: web
    path: /metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - observatorium
  selector:
    matchLabels:
      operated-prometheus: "true"
